/*
MIT License

Copyright  (c) 2009-2019 easyice

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/* Generated by Together */

#include "StdAfx.h"
#include "CAnalyze.h"


tables::CAnalyze::CAnalyze()
{
	InitParser();
}

tables::CAnalyze::~CAnalyze()
{

}

void tables::CAnalyze::AnalyzeTable(int table_id, const TABLE_SECTIONS& table_sections, TABLES* tables)
{
	if (m_mapTabParser[table_id] != NULL)
	{
		m_mapTabParser[table_id]->Parse(table_sections,tables);//只传一个section
	}
}

void tables::CAnalyze::InitParser()
{
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x00,&m_tabPAT));
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x01,&m_tabCAT));
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x02,&m_tabPMT));
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x03,&m_tabTSDT));

	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x40,&m_tabNIT));	//NIT actual
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x41,&m_tabNIT));	//NIT other

	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x42,&m_tabSDT));	//SDT actual
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x46,&m_tabSDT));	//SDT other

	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x4A,&m_tabBAT));

	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x4E,&m_tabEIT));	//EIT PF actual
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x4F,&m_tabEIT));	//EIT PF other

	for(int i = 0x50; i <= 0x5F; i++)
	{
		m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(i,&m_tabEIT));	//EIT Schedule actual
	}
	for(int i = 0x60; i <= 0x6F; i++)
	{
		m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(i,&m_tabEIT));	//EIT Schedule other
	}

	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x70,&m_tabTDT));
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x71,&m_tabRST));
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x72,&m_tabST));
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x73,&m_tabTOT));
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x7E,&m_tabDIT));
	m_mapTabParser.insert(map<int,CTabParserBase*>::value_type(0x7F,&m_tabSIT));

}
