/*
MIT License

Copyright  (c) 2009-2019 easyice

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/* Generated by Together */

#ifndef CPARSESECTIONTOGETHER_H
#define CPARSESECTIONTOGETHER_H

#include "tablesdefs.h"
#include "CBit.h"

namespace tables{
/**
 * 解析section共有语法结构 
 */
class CParseSectionTogether {
public:

        /**
         * 设置要解析的数据，不含TS头，不含pointer_field       与下面这个函数二选一来用
         */
        void SetData(BYTE* pData, int nLength = 183);

		/**
         * 设置要解析的数据，完整的TS包
         */
		bool SetPacket(BYTE* pData);
		
		/**
         * 设置要解析的完整TS包（含有段头的）后，获取有效负载部分内容（表数据）
         */
		void GetData(vector<BYTE>& vecData);

		int GetDataLen();

        BYTE Get_table_id();

        int Get_section_length();

        BYTE Get_section_number();

        BYTE Get_last_section_number();

        ~CParseSectionTogether();

        CParseSectionTogether();
public:
        BYTE* m_pData;	//指向有效负载
		BYTE* m_pPacket; //完整的TS包

		int m_nAvailable;//有效负载长度

};

}
#endif //CPARSESECTIONTOGETHER_H
