/*
MIT License

Copyright  (c) 2009-2019 easyice

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/* Generated by Together */

#ifndef CTABPARSERBASE_H
#define CTABPARSERBASE_H

#include "tablesdefs.h"
#include "CBit.h"
#include "../CDescriptor.h"

namespace tables{
/**
 * 表解析基类
 */
class CTabParserBase {
public:

        /**
         * 解析某个表
         * 传入某个表的所有section数据  (修改为只传入一个section)
         * 由子类确定解析后的数据存放到 tables的哪个成员
         */
        virtual void Parse(const TABLE_SECTIONS& table_sections, TABLES* tables) = 0;

		//只传一个section
		virtual void Parse(const SECTION& section, TABLES* tables) = 0;

        virtual ~CTabParserBase() = 0;

        CTabParserBase();

};

}
#endif //CPARSERBASE_H
