/*
MIT License

Copyright  (c) 2009-2019 easyice

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/* Generated by Together */

#include "StdAfx.h"
#include "CTabPMT.h"


tables::CTabPMT::~CTabPMT(){}
tables::CTabPMT::CTabPMT(){}


void tables::CTabPMT::Parse(const SECTION& section, TABLES* tables)
{

}

void tables::CTabPMT::Parse(const TABLE_SECTIONS& table_sections, TABLES* tables)
{

	STU_SECTION_PMT tabPMT;

	TABLE_SECTIONS::const_iterator it;

	for (it = table_sections.begin(); it != table_sections.end(); it++)
	{
		ParseSection(it->vecData,tabPMT);
	}

	if (tabPMT.empty())
	{
		return;
	}

	bool bfinded_tableid = false;
	map<int,STU_SECTION_PMT>::iterator it_tab = tables->mapTabPMT.begin();
	for (; it_tab != tables->mapTabPMT.end(); ++it_tab)
	{
		if (it_tab->second.empty())
		{
			continue;
		}
		if (it_tab->second.begin()->table_id != tabPMT.begin()->table_id)
		{
			continue;
		}
		bfinded_tableid = true;

		STU_SECTION_PMT::iterator it_sec = it_tab->second.begin();
		bool b_section_num_exist = false;
		bool b_version_num_exist = false;
		bool b_program_number_exist = false;
		for (; it_sec != it_tab->second.end(); ++it_sec)
		{
			if (it_sec->program_number == tabPMT.begin()->program_number)
			{
				b_program_number_exist = true;
			}
			if (it_sec->section_number == tabPMT.begin()->section_number)
			{
				b_section_num_exist = true;
			}
			if (it_sec->version_number == tabPMT.begin()->version_number)
			{
				b_version_num_exist = true;;
			}
		}
		

		if (!b_program_number_exist)
		{
			//DecodeDescriptors(tabPMT);
			pair< map<int,STU_SECTION_PMT>::iterator, bool > pr = tables->mapTabPMT.insert(map<int,STU_SECTION_PMT>::value_type(tabPMT[0].program_number,tabPMT));
			if (pr.second)
			{
				DecodeDescriptors(pr.first->second.back());
			}
			return;
		}
		//table_id一定是2.暂不处理版本号
		if (/*(it_tab->second.begin()->table_id == tabPMT.begin()->table_id ) &&*/ (!b_section_num_exist /*|| !b_version_num_exist*/) )
		{
			
			it_tab->second.push_back(tabPMT.front());
			DecodeDescriptors(it_tab->second.back());
			return;
		}
	
	}

	
	if (!bfinded_tableid)
	{
		//tables->vecTabPMT.push_back(tabPMT);
		
		pair< map<int,STU_SECTION_PMT>::iterator, bool > pr = tables->mapTabPMT.insert(map<int,STU_SECTION_PMT>::value_type(tabPMT[0].program_number,tabPMT));
		if (pr.second)
		{
			DecodeDescriptors(pr.first->second.back());
		}
	}

	//tables->vecTabPMT.push_back(tabPMT);
	
}

void tables::CTabPMT::ParseSection(const vector<BYTE>& vecData,STU_SECTION_PMT& tabPMT)
{
	PMT        p;
	PMT_LIST2  p2;
	int        len1,len2;
	u_char* b = (u_char*)&vecData[0];

	p.table_id 			 = b[0];
	p.section_syntax_indicator	 = CBit::getBits (b, 0, 8, 1);
	p.b_null			 = CBit::getBits (b, 0, 9, 1);
	p.reserved_1 			 = CBit::getBits (b, 0, 10, 2);
	p.section_length		 = CBit::getBits (b, 0, 12, 12);
	p.program_number		 = CBit::getBits (b, 0, 24, 16);
	p.reserved_2 			 = CBit::getBits (b, 0, 40, 2);
	p.version_number 		 = CBit::getBits (b, 0, 42, 5);
	p.current_next_indicator	 = CBit::getBits (b, 0, 47, 1);
	p.section_number 		 = CBit::getBits (b, 0, 48, 8);
	p.last_section_number 		 = CBit::getBits (b, 0, 56, 8);
	p.reserved_3	 		 = CBit::getBits (b, 0, 64, 3);
	p.pcr_pid	 		 = CBit::getBits (b, 0, 67, 13);
	p.reserved_4	 		 = CBit::getBits (b, 0, 80, 4);
	p.program_info_length 		 = CBit::getBits (b, 0, 84, 12);

	if (p.table_id != 0x02)
	{
		return;
	}

	len1 = p.section_length - 9;
	b   += 9 + 3;

	len2 = p.program_info_length;

	//p.descriptors = CDescriptor::GetInstancePtr()->DecodeDescriptor(b,len2);
	if (len2>0)
	{
		p.vec_descriptor.resize(len2);
		memcpy(&p.vec_descriptor[0],b,len2);
	}
	while (len2 > 0)
	{
		int x = 1;

		//x = descriptor (b, DVB_SI);
		//p.vec_descriptor.push_back(*b);
		len2 -= x;
		b += x;
		len1 -= x;
	}

	while (len1 > 4)
	{

		p2.stream_type		 = CBit::getBits (b, 0,  0,  8);
		p2.reserved_1		 = CBit::getBits (b, 0,  8,  3);
		p2.elementary_PID		 = CBit::getBits (b, 0, 11, 13);
		p2.reserved_2		 = CBit::getBits (b, 0, 24,  4);
		p2.ES_info_length		 = CBit::getBits (b, 0, 28, 12);

		b    += 5;
		len1 -= 5;
		len2 = p2.ES_info_length;

		//p2.descriptors = CDescriptor::GetInstancePtr()->DecodeDescriptor(b,len2);
		if (len2>0)
		{
			p2.vec_descriptor.resize(len2);
			memcpy(&p2.vec_descriptor[0],b,len2);
		}
		while (len2 > 0)
		{
			int x = 1;

			//x = descriptor (b, DVB_SI);
			//p2.vec_descriptor.push_back(*b);
			len2 -= x;
			len1 -= x;
			b += x;
		}
		
		p.vec_pmt_list2.push_back(p2);
	} // while len1

	p.crc		 		 = CBit::getBits (b, 0, 0, 32);

	tabPMT.push_back(p);
}

//void tables::CTabPMT::DecodeDescriptors(STU_SECTION_PMT& tabPMT)
//{
//	if (tabPMT.empty())
//	{
//		return;
//	}
//
//	if (!tabPMT.begin()->vec_descriptor.empty())
//	{
//		CDescriptor::GetInstancePtr()->DecodeDescriptor(tabPMT.begin()->descriptors,&tabPMT.begin()->vec_descriptor[0],(int)tabPMT.begin()->vec_descriptor.size());	
//	}
//
//	vector<PMT_LIST2>::iterator it = tabPMT.begin()->vec_pmt_list2.begin();
//	for (; it != tabPMT.begin()->vec_pmt_list2.end();++it)
//	{
//		if (!it->vec_descriptor.empty())
//		{
//			CDescriptor::GetInstancePtr()->DecodeDescriptor(it->descriptors,&it->vec_descriptor[0],(int)it->vec_descriptor.size());
//		}
//	}
//}
//

void tables::CTabPMT::DecodeDescriptors(PMT& pmt)
{
	if (!pmt.vec_descriptor.empty())
	{
		CDescriptor::GetInstancePtr()->DecodeDescriptor(pmt.descriptors,&pmt.vec_descriptor[0],(int)pmt.vec_descriptor.size());	
	}

	vector<PMT_LIST2>::iterator it = pmt.vec_pmt_list2.begin();
	for (; it != pmt.vec_pmt_list2.end();++it)
	{
		if (!it->vec_descriptor.empty())
		{
			CDescriptor::GetInstancePtr()->DecodeDescriptor(it->descriptors,&it->vec_descriptor[0],(int)it->vec_descriptor.size());
		}
	}
}

