/*
MIT License

Copyright  (c) 2009-2019 easyice

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/* Generated by Together */

#ifndef CTABPMT_H
#define CTABPMT_H
#include "CTabParserBase.h"
namespace tables{
class CTabPMT : public CTabParserBase {
public:

        void Parse(const TABLE_SECTIONS& table_sections, TABLES* tables);

		void Parse(const SECTION& section, TABLES* tables);

        ~CTabPMT();

        CTabPMT();

private:
		void ParseSection(const vector<BYTE>& vecData,STU_SECTION_PMT& tabPMT);
		//void DecodeDescriptors(STU_SECTION_PMT& tabPMT);
		void DecodeDescriptors(PMT& pmt);
};

}
#endif //CTABPMT_H
