/*
MIT License

Copyright  (c) 2009-2019 easyice

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/* Generated by Together */

#include "StdAfx.h"
#include "CTabCAT.h"

tables::CTabCAT::~CTabCAT()
{

}

tables::CTabCAT::CTabCAT()
{

}

void tables::CTabCAT::Parse(const SECTION& section, TABLES* tables)
{

}

void tables::CTabCAT::Parse(const TABLE_SECTIONS& table_sections, TABLES* tables)
{
	STU_SECTION_CAT tabCAT;

	TABLE_SECTIONS::const_iterator it;

	for (it = table_sections.begin(); it != table_sections.end(); it++)
	{
		ParseSection(it->vecData,tabCAT);
	}
	if (tabCAT.empty())
	{
		return;
	}

	bool bfinded_tableid = false;
	vector<STU_SECTION_CAT>::iterator it_tab = tables->vecTabCAT.begin();
	for (; it_tab != tables->vecTabCAT.end(); ++it_tab)
	{
		if (it_tab->empty())
		{
			continue;
		}
		if (it_tab->begin()->table_id != tabCAT.begin()->table_id)
		{
			continue;
		}

		bfinded_tableid = true;

		bool b_section_num_exist = false;
		bool b_version_num_exist = false;

		STU_SECTION_CAT::iterator it_sec = it_tab->begin();

		for (; it_sec != it_tab->end(); ++it_sec)
		{
			if (it_sec->section_number == tabCAT.begin()->section_number)
			{
				b_section_num_exist = true;
			}
			
			if (it_sec->version_number == tabCAT.begin()->version_number)
			{
				b_version_num_exist = true;;
			}
		}
		
		//如果需要处理不同版本号打开注释。暂不处理版本号
		if ((it_tab->begin()->table_id == tabCAT.begin()->table_id )&& ( !b_section_num_exist /*|| !b_version_num_exist*/ ))
		{
			it_tab->push_back(tabCAT.front());
			DecodeDescriptors(it_tab->back());
			return;
		}
	
	}

	if (!bfinded_tableid)
	{
		
		tables->vecTabCAT.push_back(tabCAT);
		DecodeDescriptors(tables->vecTabCAT.back().back());
	}

}

void tables::CTabCAT::ParseSection(const vector<BYTE>& vecData,STU_SECTION_CAT& tabCAT)
{
	//解析一个section,push_back到tabCAT
	CAT  c;
	int  len1;
	u_char* b = (u_char*)&vecData[0];

	c.table_id 			 = b[0];
	c.section_syntax_indicator	 = CBit::getBits (b, 0, 8, 1);
	c.reserved_1 			 = CBit::getBits (b, 0, 10, 2);
	c.section_length		 = CBit::getBits (b, 0, 12, 12);
	c.reserved_2 			 = CBit::getBits (b, 0, 24, 18);
	c.version_number 		 = CBit::getBits (b, 0, 42, 5);
	c.current_next_indicator	 = CBit::getBits (b, 0, 47, 1);
	c.section_number 		 = CBit::getBits (b, 0, 48, 8);
	c.last_section_number 		 = CBit::getBits (b, 0, 56, 8);

	if (c.table_id != 0x01)
	{
		return;
	}

	// buffer + header, len = len - header - CRC
	// Descriptor ISO 13818 - 2.6.1


	// - header - CRC
	len1 = c.section_length - 5;
	b  += 8;

	//c.descriptors = CDescriptor::GetInstancePtr()->DecodeDescriptor(b,len1-4);
	if (len1-4 > 0)
	{
		c.vec_descriptor.resize(len1-4);
		memcpy(&c.vec_descriptor[0],b,len1-4);
	}

	while (len1 > 4)
	{
		int i = 1;

		//i     =  descriptor (b, MPEG);
//		c.vec_descriptor.push_back(*b);
		len1 -= i;
		b    += i;

	}
	
	c.CRC 		 = CBit::getBits (b, 0, 0, 32);

	tabCAT.push_back(c);
}

//void tables::CTabCAT::DecodeDescriptors(STU_SECTION_CAT& tabCAT)
//{
//	if (tabCAT.empty())
//	{
//		return;
//	}
//	if (!tabCAT.begin()->vec_descriptor.empty())
//	{
//		CDescriptor::GetInstancePtr()->DecodeDescriptor(tabCAT.begin()->descriptors,&tabCAT.begin()->vec_descriptor[0],(int)tabCAT.begin()->vec_descriptor.size());	
//	}
//}

void tables::CTabCAT::DecodeDescriptors(CAT& cat)
{

	if (!cat.vec_descriptor.empty())
	{
		CDescriptor::GetInstancePtr()->DecodeDescriptor(cat.descriptors,&cat.vec_descriptor[0],(int)cat.vec_descriptor.size());	
	}
}
