/*
MIT License

Copyright  (c) 2009-2019 easyice

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/* Generated by Together */

#include "StdAfx.h"
#include "CTabPAT.h"

tables::CTabPAT::CTabPAT()
{

}

tables::CTabPAT::~CTabPAT()
{

}

void tables::CTabPAT::Parse(const SECTION& section, TABLES* tables)
{

}

void tables::CTabPAT::Parse(const TABLE_SECTIONS& table_sections, TABLES* tables)
{

	STU_SECTION_PAT tabPAT;

	TABLE_SECTIONS::const_iterator it;

	for (it = table_sections.begin(); it != table_sections.end(); it++)
	{
		ParseSection(it->vecData,tabPAT);
	}

	if (tabPAT.empty())
	{
		return;
	}

	bool bfinded_tableid = false;
	vector<STU_SECTION_PAT>::iterator it_tab = tables->vecTabPAT.begin();
	for (; it_tab != tables->vecTabPAT.end(); ++it_tab)
	{
		if (it_tab->empty())
		{
			continue;
		}
		if (it_tab->begin()->table_id != tabPAT.begin()->table_id)
		{
			continue;
		}

		bfinded_tableid = true;

		bool b_section_num_exist = false;
		bool b_version_num_exist = false;

		STU_SECTION_PAT::iterator it_sec = it_tab->begin();

		for (; it_sec != it_tab->end(); ++it_sec)
		{
			if (it_sec->section_number == tabPAT.begin()->section_number)
			{
				b_section_num_exist = true;
			}
			
			if (it_sec->version_number == tabPAT.begin()->version_number)
			{
				b_version_num_exist = true;;
			}
		}
		
		if ((it_tab->begin()->table_id == tabPAT.begin()->table_id )&& ( !b_section_num_exist || !b_version_num_exist ))
		{
			it_tab->push_back(tabPAT.front());
			return;
		}
	
	}

	if (!bfinded_tableid)
	{
		tables->vecTabPAT.push_back(tabPAT);
	}

}

void  tables::CTabPAT::ParseSection(const vector<BYTE>& vecData,STU_SECTION_PAT& tabPAT)
{
	PAT p;
	PAT_LIST pl;
	int n;
	u_char* b = (u_char*)&vecData[0];

	p.table_id 			 = b[0];
	p.section_syntax_indicator	 = CBit::getBits (b, 0, 8, 1);
	p.reserved_1 			 = CBit::getBits (b, 0, 10, 2);
	p.section_length		 = CBit::getBits (b, 0, 12, 12);
	p.transport_stream_id		 = CBit::getBits (b, 0, 24, 16);
	p.reserved_2 			 = CBit::getBits (b, 0, 40, 2);
	p.version_number 		 = CBit::getBits (b, 0, 42, 5);
	p.current_next_indicator	 = CBit::getBits (b, 0, 47, 1);
	p.section_number 		 = CBit::getBits (b, 0, 48, 8);
	p.last_section_number 		 = CBit::getBits (b, 0, 56, 8);

	if (p.table_id != 0x00)
	{
		return;
	}

	// PID list...
	// n = section_length - CRC  - front bytes
	// n = len / anzahl bytes pro pid angabe.
	// Buffer to start of List

	n  = p.section_length - 5 - 4;

	b = b + 8;

	for (; n>=4; n=n-4)
	{
		pl.program_number	 = CBit::getBits (b, 0, 0, 16);
		pl.reserved		 = CBit::getBits (b, 0, 16, 3);
		pl.network_pmt_PID	 = CBit::getBits (b, 0, 19, 13);
		b += 4;

		p.vec_pat_list.push_back(pl);
	}

	 p.CRC = CBit::getBits (b,0,0,32);

	 tabPAT.push_back(p);
}
